---
- name: Load balancer provision
  hosts: control
  become: true
  gather_facts: false
  roles:
    - haproxy
    - keepalived
    - etcdctl

- name: Kubernetes provision
  hosts: [control, worker]
  become: true
  gather_facts: false
  roles:
    - disable_swap
    - docker_repo
    - kubernetes

- name: Worker provison
  hosts: [worker]
  become: true
  gather_facts: false
  roles:
    - disk_label
    - mount
    - longhorn

- name: Kubernetes backup
  hosts: control
  become: true
  gather_facts: false
  roles:
    - kubernetes_backup
...
