---
- name: Load kernel modules
  community.general.modprobe:
    name: '{{ item.key }}'
    params: '{{ item.value | default(omit, True) }}'
    persistent: present
    state: present
  loop: '{{ modprobe_load | ansible.builtin.dict2items }}'
  loop_control:
    label: '{{ item.key }}'
  tags: [modprobe]
...
